apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: postgrescompositeworkloads.gitops.bluesolution.es
spec:
  scope: Cluster
  group: gitops.bluesolution.es
  names:
    kind: PostgresCompositeWorkload
    plural: postgrescompositeworkloads
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string
                label:
                  type: object
                  properties:
                    postgresNamespace:
                      type: string
