version: "3"

vars:
  items: ["video-streaming"]
  factory: ""
  output: ""

tasks:
  generate:chart:
    cmds:
      - mkdir -p output/charts/{{.item}}
      - kcl run factory/chart_builder.k -D chart=\"{{.item}}\" -o output/charts/{{.item}}/Chart.yaml

  generate:values:
    cmds:
      - mkdir -p output/charts/{{.item}}
      - touch output/charts/{{.item}}/values.yaml

  generate:templates:
    cmds:
      - mkdir -p output/charts/{{.item}}/templates
      - kcl run factory/templates_builder.k -D chart=\"{{.item}}\" -o output/charts/{{.item}}/templates/manifests.yaml

  generate:helmfile:
    cmds:
      - kcl run factory/helmfile_builder.k -o  output/helmfile.yaml

  generate:all:
    cmds:
      - |
        nu -c '
        let items = {{.items | toJson}}
        for item in $items {
          echo $"Generating chart for ($item)"
          ^task generate:chart item=$item
          ^task generate:values item=$item
          ^task generate:templates item=$item
        }
        ^task generate:helmfile
        '    
  