#https://kafka-strimzi.io/docs/installation/helm/
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xkafkastrimzi-composition
spec:
  compositeTypeRef:
    apiVersion: koncept.bluesolution.es/v1alpha1
    kind: XKafkaStrimzi
  resources:
    - name: kafka-strimzi-helm-release
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          name: kafka-strimzi
        spec:
          forProvider:
            chart:
              name: strimzi-kafka-operator
              repository: oci://quay.io/strimzi-helm
              version: 0.46.0
            createNamespace: true
            set:
              - name: installCRDs
                value: "true"
          providerConfigRef:
            name: helm-provider
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.namespace"
          toFieldPath: "spec.forProvider.namespace"

