package scaffold

// projectFile is a single templated file in the generated project skeleton.
type projectFile struct {
	name    string
	path    string
	content string
}

// projectFiles is the ordered set of files written by Generate. Paths are
// POSIX-style and relative to the project root (destRoot/<slug>).
var projectFiles = []projectFile{
	{"koncept_yaml", "koncept.yaml", tplKonceptYaml},
	{"kcl.mod", "kcl.mod", tplKclMod},
	{"main.k", "main.k", tplMainK},
	{"core_configs", "core_sources/{{.Slug}}_configurations.k", tplCoreConfigurations},
	{"kernel_configs", "kernel/configurations.k", tplKernelConfigurations},
	{"kernel_project", "kernel/project_def.k", tplKernelProject},
	{"module_def", "modules/appops/{{.AppPackage}}/{{.AppPackage}}_module_def.k", tplModuleDef},
	{"stack", "stacks/{{.Slug}}_stack.k", tplStack},
	{"dev_stack_def", "stacks/development/stack_def.k", tplDevStackDef},
	{"dev_profile_configs", "stacks/development/profile_configurations.k", tplDevProfileConfigs},
	{"dev_profile_def", "stacks/development/profile_def.k", tplDevProfileDef},
	{"tenant_def", "tenants/vendor/tenant_def.k", tplTenantDef},
	{"site_configs", "sites/development/dev_cluster/configurations.k", tplSiteConfigs},
	{"site_def", "sites/development/dev_cluster/site_def.k", tplSiteDef},
	{"pre_releases_mod", "pre_releases/kcl.mod", tplPreReleasesMod},
	{"pre_releases_configs", "pre_releases/configurations_dev.k", tplPreReleaseConfigs},
	{"render", "pre_releases/manifests/dev/factory/render.k", tplRenderK},
	{"factory_seed", "pre_releases/manifests/dev/factory/factory_seed.k", tplFactorySeed},
}

// The path templates are rendered separately; store the raw templates and resolve
// them in Generate via renderTemplate on f.path too.

const tplKclMod = `[package]
name = "{{.Slug}}"
edition = "v0.10.0"
version = "0.1.0"

[dependencies]
framework = { path = "{{.FrameworkPath}}" }
k8s = "1.31.2"
`

const tplKonceptYaml = `apiVersion: koncept.bluesolution.es/v1
kind: ProjectConfig
metadata:
  name: {{.Slug}}
  version: "0.1.0"
spec:
  frameworkPath: "{{.FrameworkPath}}"
  framework:
    source: local
    version: dev
    versionConstraint: "{{.FrameworkVersionConstraint}}"
    supportTier: "{{.FrameworkSupportTier}}"
    supportWindow: "until next minor framework release"
    testedVersions:
      - dev
  defaultOutput: yaml
  factory:
    seedFile: factory_seed.k
    renderFile: render.k
  output:
    defaultDir: output
  backstage:
    owner: {{.BackstageOwner}}
    lifecycle: experimental
`

const tplMainK = `"""
{{.DisplayName}} — generated by koncept init project.

A webapp golden-path project skeleton:
  kernel -> profile -> tenant -> site -> pre_release (dev) -> factory output.

Render the dev environment:
  koncept render argocd --factory pre_releases/manifests/dev/factory
"""
`

const tplCoreConfigurations = `"""
{{.DisplayName}} project-specific configuration schema.
Extends BaseConfigurations with project-specific fields.
"""

import framework.models.configurations as base

schema {{.SchemaPrefix}}Configurations(base.BaseConfigurations):
    appProfile?: str = "default"
`

const tplKernelConfigurations = `import file
import framework.factory.conventions as conventions
import {{.Slug}}.core_sources.{{.Slug}}_configurations as cfg

_{{.Slug}}_kernel_configurations = cfg.{{.SchemaPrefix}}Configurations {
    projectName = conventions.project_slug_from_path(file.current())
    gitRepoUrl = "{{.GitRepoURL}}"
    backstageOwner = "{{.BackstageOwner}}"
}
`

const tplKernelProject = `import framework.models.project
import {{.Slug}}.kernel.configurations

{{.Slug}}_project = project.Project {
    name = "{{.DisplayName}}"
    description = "{{.DisplayName}} — generated by koncept init project"
    configurations = configurations._{{.Slug}}_kernel_configurations
}
`

const tplModuleDef = `"""
{{.DisplayName}} web application module.
Uses the WebAppModule template from framework.
"""
import framework.templates.webapp.v1_0_0.webapp as webapp
import framework.builders.deployment as deploy

schema {{.SchemaPrefix}}ApiModule(webapp.WebAppModule):
    port = {{.Port}}
    serviceType = "ClusterIP"
    replicas = 1
    imagePullPolicy = "IfNotPresent"

    resources = deploy.ResourceSpec {
        cpuRequest = "100m"
        cpuLimit = "1"
        memoryRequest = "256Mi"
        memoryLimit = "512Mi"
    }

    livenessProbe = deploy.ProbeSpec {
        probeType = "http"
        path = "/healthz"
        port = {{.Port}}
        initialDelaySeconds = 10
        periodSeconds = 10
    }

    readinessProbe = deploy.ProbeSpec {
        probeType = "http"
        path = "/readyz"
        port = {{.Port}}
        initialDelaySeconds = 5
        periodSeconds = 5
    }

    env = [
        {
            name = "APP_PROFILE"
            value = configurations.appProfile if configurations.appProfile else "default"
        }
    ]
`

const tplStack = `"""
Shared {{.DisplayName}} stack template.
Profile-specific folders override only the values that differ.
"""

import framework.models.stack
import framework.models.compatibility as compat
import framework.assembly.helpers as asm
import {{.Slug}}.modules.appops.{{.AppPackage}}.{{.AppPackage}}_module_def as {{.AppPackage}}

schema {{.SchemaPrefix}}Stack(stack.Stack):
    appImage: str = "{{.Image}}"
    appVersion: str = "{{.Version}}"
    compatibility = compat.FrameworkCompatibility {
        version = "dev"
        versionConstraint = "{{.FrameworkVersionConstraint}}"
        supportTier = "{{.FrameworkSupportTier}}"
        source = "local"
        supportWindow = "until next minor framework release"
    }

    _apps_namespace = asm.create_namespace(instanceConfigurations.appsNamespace, instanceConfigurations)

    k8snamespaces = [_apps_namespace]

    _app = {{.AppPackage}}.{{.SchemaPrefix}}ApiModule {
        name = "{{.AppName}}"
        namespace = _apps_namespace.name
        asset = {
            image = appImage
            version = appVersion
        }
        configurations = instanceConfigurations
        dependsOn = [_apps_namespace]
    }.instance

    components = [_app]
    accessories = []
`

const tplDevStackDef = `"""{{.DisplayName}} development stack — only profile-specific overrides live here."""

import {{.Slug}}.stacks.{{.Slug}}_stack as common

schema Stack(common.{{.SchemaPrefix}}Stack):
    # Override image tags or sizing for development here.

schema {{.SchemaPrefix}}DevelopmentStack(Stack):
    # Backward-compatible alias for existing imports.
`

const tplDevProfileConfigs = `import {{.Slug}}.core_sources.{{.Slug}}_configurations as cfg

_{{.Slug}}_profile_configurations = cfg.{{.SchemaPrefix}}Configurations {
    appsNamespace = "{{.AppsNamespace}}"
    appProfile = "dev"
}
`

const tplDevProfileDef = `import file
import framework.factory.conventions as conventions
import {{.Slug}}.core_sources.{{.Slug}}_configurations as cfg
import {{.Slug}}.stacks.development.profile_configurations

profile = conventions.build_profile(conventions.ProfileSpec {
    currentFile = file.current()
    configurations = cfg.{{.SchemaPrefix}}Configurations {
        **profile_configurations._{{.Slug}}_profile_configurations
    }
})

{{.Slug}}_development_profile = profile
`

const tplTenantDef = `import file
import framework.factory.conventions as conventions
import {{.Slug}}.core_sources.{{.Slug}}_configurations as cfg

tenant = conventions.build_tenant(conventions.TenantSpec {
    currentFile = file.current()
    name = "Internal"
    description = "Internal vendor/development team"
    configurations = cfg.{{.SchemaPrefix}}Configurations {
        brandIcon = "internal-logo"
    }
})

tenant_vendor = tenant
`

const tplSiteConfigs = `import {{.Slug}}.core_sources.{{.Slug}}_configurations as cfg

_dev_cluster_site_configurations = cfg.{{.SchemaPrefix}}Configurations {
    siteName = "dev_cluster"
    storageClassName = "local-path"
    useLocalPersistentVolumes = True
}
`

const tplSiteDef = `import file
import framework.factory.conventions as conventions
import {{.Slug}}.tenants.vendor.tenant_def as tenant_def
import {{.Slug}}.core_sources.{{.Slug}}_configurations as cfg
import {{.Slug}}.sites.development.dev_cluster.configurations

site = conventions.build_site(conventions.SiteSpec {
    currentFile = file.current()
    tenant = tenant_def.tenant
    configurations = cfg.{{.SchemaPrefix}}Configurations {
        **configurations._dev_cluster_site_configurations
    }
})

dev_cluster_site = site
`

const tplPreReleasesMod = `[package]
name = "pre_releases"
edition = "v0.10.0"
version = "0.1.0"

[dependencies]
{{.Slug}} = { path = "../../{{.Slug}}" }
`

const tplPreReleaseConfigs = `"""
Pre-release configurations for dev cluster — merges all 4 configuration layers.
"""

import {{.Slug}}.stacks.development.stack_def
import {{.Slug}}.stacks.development.profile_def
import {{.Slug}}.tenants.vendor
import {{.Slug}}.sites.development.dev_cluster.site_def
import {{.Slug}}.kernel.project_def
import framework.models.configurations as base

_tenant = vendor.tenant_vendor
_project = project_def.{{.Slug}}_project
_site = site_def.dev_cluster_site
_profile = profile_def.{{.Slug}}_development_profile

_pre_release_configurations_dev_cluster = base.merge_configurations(_project.configurations, _profile.configurations, _tenant.configurations, _site.configurations)

_stack = stack_def.{{.SchemaPrefix}}DevelopmentStack {
    instanceConfigurations = _pre_release_configurations_dev_cluster
}
`

const tplRenderK = `"""Factory render wrapper that delegates to framework.factory.render_entry."""
import framework.factory.render_entry as render_entry
import .factory_seed as factory_ctx

_output = option("output", default="yaml")

render_entry.render_from_seed(
	factory_ctx._stack
	factory_ctx._project_name
	factory_ctx._git_repo_url
	factory_ctx._manifest_path
	_output
)
`

const tplFactorySeed = `"""
Factory seed for {{.Slug}} dev pre-release.
Contract exports: _stack, _project_name, _git_repo_url, _manifest_path
"""

import file
import framework.factory.conventions as conventions
import framework.factory.seed as seed
import {{.Slug}}.stacks.development.stack_def
import {{.Slug}}.stacks.development.profile_def
import {{.Slug}}.tenants.vendor.tenant_def
import {{.Slug}}.sites.development.dev_cluster.site_def
import {{.Slug}}.kernel.project_def

_context = conventions.context_from_path(file.current())

_factory = seed.FactorySeed {
    project = project_def.{{.Slug}}_project
    profile = profile_def.profile
    tenant = tenant_def.tenant
    site = site_def.site
    stackSchema = stack_def.Stack
    version = _context.version
    releaseName = _context.releaseName
    manifestPath = _context.manifestPath
}

_stack = _factory.renderStack
_project_name = _factory.projectName
_git_repo_url = _factory.gitRepoUrl
_manifest_path = _factory.manifestPath
`
