apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xcertmanager-composition
spec:
  compositeTypeRef:
    apiVersion: koncept.bluesolution.es/v1alpha1
    kind: XCertManager
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: namespaceCertManager
            base:
              apiVersion: kubernetes.crossplane.io/v1alpha2
              kind: Object
              spec:
                providerConfigRef:
                  name: provider-kubernetes
                forProvider:
                  manifest:
                    apiVersion: v1
                    kind: Namespace
                    metadata:
                      name: cert-manager
          - name: cert-manager-helm-release
            base:
              apiVersion: helm.crossplane.io/v1beta1
              kind: Release
              metadata:
                name: cert-manager
              spec:
                providerConfigRef:
                  name: helm-provider
                forProvider:
                  chart:
                    name: cert-manager
                    repository: https://charts.jetstack.io
                    # use a chart version string (check latest that you want). Example:
                    version: "v1.17.2"
                  set:
                    - name: installCRDs
                      value: "true"
            patches:
              # patch the namespace value from the XR into the Release namespace
              - type: FromCompositeFieldPath
                fromFieldPath: spec.namespace
                toFieldPath: spec.forProvider.namespace
              # optionally, ensure the Release metadata.namespace is set to the same
              - type: FromCompositeFieldPath
                fromFieldPath: spec.namespace
                toFieldPath: metadata.namespace
    - step: automatically-detect-readiness
      functionRef:
        name: function-auto-ready
