version: "3"

tasks:
  generate:manifests:
    cmds:
      - mkdir -p output
      - kcl run factory/kubernetes_manifests_builder.k -o output/kubernetes_manifests.yaml

  generate:application:
    cmds:
      - kcl run factory/argocd_builder.k -o output/argocd.yaml

  generate:all:
    deps:
      - generate:manifests
      - generate:application
