apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xkeycloaks.koncept.bluesolution.es
spec:
  compositeTypeRef:
    apiVersion: koncept.bluesolution.es/v1alpha1
    kind: XKeycloak
  mode: Pipeline
  pipeline:
    - step: create-namespace
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: namespaceKeycloak
            base:
              apiVersion: kubernetes.crossplane.io/v1alpha2
              kind: Object
              spec:
                forProvider:
                  manifest:
                    apiVersion: v1
                    kind: Namespace
                    metadata:
                      name: keycloak
                providerConfigRef:
                  name: provider-kubernetes
    - step: automatically-detect-readiness
      functionRef:
        name: function-auto-ready
    - step: create-keycloak
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: keycloak-instance
            base:
              apiVersion: kubernetes.crossplane.io/v1alpha2
              kind: Object
              spec:
                providerConfigRef:
                  name: provider-kubernetes
                forProvider:
                  manifest:
                    apiVersion: k8s.keycloak.org/v1
                    kind: Keycloak
                    metadata:
                      name: keycloak
                      namespace: keycloak
                    spec:
                      db:
                        database: blue_postgres
                        host: blue-postgres.postgres.svc.cluster.local
                        password: postgres
                        user: postgres
                        vendor: postgres
                      ingress:
                        enabled: true
                        hostname: bluesolution.es
                      instances: 1
            patches:
              - fromFieldPath: "spec.label.namespace"
                toFieldPath: "spec.forProvider.manifest.metadata.namespace"
                policy:
                  fromFieldPath: "Required"
              - type: FromCompositeFieldPath
                fromFieldPath: spec.hostname
                toFieldPath: spec.forProvider.manifest.spec.ingress.hostname
              - type: FromCompositeFieldPath
                fromFieldPath: spec.replicas
                toFieldPath: spec.forProvider.manifest.spec.instances
              - type: FromCompositeFieldPath
                fromFieldPath: spec.namespace
                toFieldPath: spec.forProvider.manifest.metadata.namespace
              # - type: FromCompositeFieldPath
              #   fromFieldPath: metadata.namespace
              #   toFieldPath: spec.forProvider.namespace
              # - type: FromCompositeFieldPath
              #   fromFieldPath: metadata.namespace
              #   toFieldPath: metadata.namespace
