apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: xkeycloaks.koncept.bluesolution.es
spec:
  scope: Cluster
  group: koncept.bluesolution.es
  names:
    kind: XKeycloak
    plural: xkeycloaks
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                hostname:
                  type: string
                  description: Base hostname for Keycloak ingress.
                replicas:
                  type: integer
                  description: Number of Keycloak replicas.
                  default: 1
                namespace:
                  type: string
                label:
                  type: object
                  properties:
                    namespace:
                      type: string
              required:
                - hostname
