#https://cert-manager.io/docs/installation/helm/
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xcertmanager-composition
spec:
  compositeTypeRef:
    apiVersion: koncept.bluesolution.es/v1alpha1
    kind: XCertManager
  resources:
    - name: cert-manager-helm-release
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          name: cert-manager
        spec:
          forProvider:
            chart:
              name: cert-manager
              repository: https://charts.jetstack.io
              version: v1.17.2
            namespace: cert-manager
            set:
              - name: installCRDs
                value: "true"
          providerConfigRef:
            name: helm-provider
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.namespace"
          toFieldPath: "spec.forProvider.namespace"
