apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: xkafkastrimzis.koncept.bluesolution.es
spec:
  group: koncept.bluesolution.es
  names:
    kind: XKafkaStrimzi
    plural: xkafkastrimzis
  claimNames:
    kind: KafkaStrimzi
    plural: kafkastrimzis
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string
